usocket/usocket

- backend/sbcl.lisp
sockint::fd->handle has been a no-op for a long time and now its usage results in a warning.
> Remove usage of deprecated functions on sbcl-windows.

- backend/openmcl.lisp
Hi,
the other day I was playing with [cl-redis](https://github.com/vseloved/cl-redis) on CCL 1.10. I ran into the bug, that sockets cannot be created in CCL with vector quad hosts. 
Steps to reproduce this bug:
1. Load `usocket` into your CCL image (obviously)
2. Run 
```lisp
CL-USER> (usocket:socket-connect #(127 0 0 1) 6379) ; default Redis host and port
```
This presents me:
```
The value #(127 0 0 1) is not of the expected type (OR
INTEGER
STRING).
[Condition of type TYPE-ERROR]
Restarts:
0: [RETRY] Retry SLIME REPL evaluation request.
1: [*ABORT] Return to SLIME's top level.
2: [ABORT-BREAK] Reset this thread
3: [ABORT] Kill this thread
Backtrace:
0: (CCL::HOST-AS-INET-HOST #(127 0 0 1))
1: (CCL::MAKE-TCP-STREAM-SOCKET 27 :REMOTE-HOST #(127 0 0 1) :REMOTE-PORT 6379 :LOCAL-HOST NIL …
```
> [CCL] Translate host to hostname

- backend/sbcl.lisp
On some platforms there is warning about implicit functio declaration
One such platform is ArchLinuxARM na armv7h - apparently socket.h doesn't have include of unistd.h, or something of this kind
> [ECL] include unistd.h for gethostname

- backend/sbcl.lisp
https://github.com/usocket/usocket/issues/11
> BUGFIX ([SBCL Windows] wait-for-input nil-timeout bug)

- backend/sbcl.lisp
Multiple `#-ecl` are confusing here.
> Style improvement to avoid nested #+ / #-

- README.md
- package.lisp
Your link to the API documentation is broken. Common-lisp.net has added SSL support on their website.
Also, the `listen` function should be external, it is listed in the API documentation as something that should be used.
Thanks!
> Fixed a broken link

- backend/abcl.lisp
On ABCL, the vector form of IPv6 addresses only included the first half
of the bytes, resulting in an 8-byte vector instead of the full 16 bytes
of the vector.
> Fixed incorrect IPv6 addresses on ABCL

- backend/clisp.lisp
cl-mongo was unable to make database queries when running in clisp. I tracked the problem down to this one line. Changing it as shown fixed things for me.
> fix wait-for-input for clisp

- backend/sbcl.lisp
In ECL (which also uses backend/sbcl.lisp) this failure to catch EINTR results
in it being passed up, which ends up as #<a USOCKET:UNKNOWN-ERROR>.
> Fix read-select in backend/sbcl.lisp to loop if interrupted

- backend/openmcl.lisp
- backend/sbcl.lisp
Lowercased ccl::rletz so this will work with (readtable-case *readtable-case*) of :invert.
> lowercased Z in ccl::rletZ

- backend/lispworks.lisp
- option.lisp
Added the get/set-broadcast calls for LispWorks. However they alone are of little help, since LW fails on COMM::CONNECT if the host parameter is the broadcast address.
Hence a check for zero-network address was added in CONNECT-TO-UDP-SERVER and appears to do the job. Hacky, so any better ideas are welcome.
> Add UDP broadcast support for LispWorks

- server.lisp
- test/test-timeout.lisp
- usocket-test.asd
These tests currently fail for all Lisp implementations I can run,
in various ways. I mostly added them to see if the usocket timeout API
actually works, seems like it doesn't really work.
> Add tests for stream timeouts

- usocket.lisp
1. Style improvement in function `split-ipv6-address`: initialize `LET` variables with `NIL`.
2. Fix in function `host-to-vector-quad`: use `LET` instead of unnecessary `LET*`.
> fix: minor improvements in usage of LET

- backend/sbcl.lisp
> ; in: DEFMETHOD SOCKET-RECEIVE (DATAGRAM-USOCKET T T)
> ; note: Type assertion too complex to check:
> ; (VALUES (SIMPLE-ARRAY (UNSIGNED-BYTE 8) (*)) UNSIGNED-BYTE
> ;         (SIMPLE-ARRAY (UNSIGNED-BYTE 8) (*)) (UNSIGNED-BYTE 16) &REST T).
> ; It allows an unknown number of values, consider using
> ; (VALUES (SIMPLE-ARRAY (UNSIGNED-BYTE 8) (*)) UNSIGNED-BYTE
> ;         (SIMPLE-ARRAY (UNSIGNED-BYTE 8) (*)) (UNSIGNED-BYTE 16) &OPTIONAL).
- Add `&OPTIONAL` to DEFMETHOD SOCKET-RECEIVE type declaration
- Now only declared values should be allowed.
> [SBCL] Fix type assertion compiler note

- backend/abcl.lisp
- backend/allegro.lisp
- backend/clisp.lisp
- backend/clozure.lisp
- backend/cmucl.lisp
- backend/genera.lisp
- backend/iolib.lisp
- backend/lispworks.lisp
- backend/mcl.lisp
- backend/mezzano.lisp
- backend/mocl.lisp
- backend/openmcl.lisp
- backend/sbcl.lisp
- backend/scl.lisp
- usocket.lisp
Add restarts to socket-connect .
Issue #99
> [socket-connect] Provide restarts to interactively set host and port

- condition.lisp
- server.lisp
- usocket.lisp
This commit goes through most of the package's exported symbols, updating docstrings where needed and adding docstrings to most undocumented functions and variables.
The following docstrings have been added or updated:
+ socket-connect
+ get-local-address
+ get-peer-address
+ socket-send
+ socket-receive
+ wait-for-input
+ make-wait-list
+ add-waiter
+ remove-waiter
+ remove-all-waiters
+ usocket-p
+ stream-usocket-p
+ stream-server-usocket-p
+ datagram-usocket-p
+ hbo-to-dotted-quad
+ hbo-to-vector-quad
+ vector-quad-to-dotted-quad
+ dotted-quad-to-vector-quad
+ vector-to-ipv6-host
+ ipv6-host-to-vector
+ ip=
+ ip/=
+ integer-to-octet-buffer
+ octet-buffer-to-integer
+ port-to-octet-buffer
+ port-from-octet-buffer
+ ip-to-octet-buffer
+ ip-from-octet-buffer
+ with-mapped-conditions
+ …
> Update and supply documentation for most exported symbols

- backend/abcl.lisp
- backend/allegro.lisp
- backend/clisp.lisp
- backend/clozure.lisp
- backend/cmucl.lisp
- backend/genera.lisp
- backend/iolib.lisp
- backend/lispworks.lisp
- backend/mcl.lisp
- backend/mezzano.lisp
- backend/mocl.lisp
- backend/openmcl.lisp
- backend/sbcl.lisp
- backend/scl.lisp
- usocket.lisp
A simple test case on SBCL 2.3.4 macOS 13.4.1:
```lisp
(defun userver ()
(let ((socket (usocket:socket-listen #p"/tmp/uds")))
(unwind-protect
(loop
(let* ((connection (usocket:socket-accept socket :element-type 'character))
(stream (usocket:socket-stream connection)))
(format stream (read-line stream))
(force-output stream)
(usocket:socket-close connection)))
(progn
(usocket:socket-close socket)
(uiop:delete-file-if-exists #p "/tmp/uds")))))
(defun create-userver ()
(bt:make-thread
#'userver
:name "usocket-server"))
(defun client ()
(usocket:with-client-socket (socket stream #p"/tmp/uds")
(unwind-protect
(progn
(format stream "Hello~&")
(force-output stream)
(format t (read-line stream)))
(usocket:socket-close socket))))
```
> support domain socket on SBCL/*nix

- usocket.lisp
The following symbols are macros defined as thin wrappers around `octet-buffer-to-integer`:
+ port-to-octet-buffer
+ ip-to-octet-buffer
+ port-from-octet-buffer
+ ip-from-octet-buffer
These macros do no real syntax transformation. These forms would better serve the user as inline functions, which would provide nearly the same effect in reducing function call overhead, while also letting them be passed around easily as function objects.
Yeah I know kinda petty, but I figure there's not much risk of breakage and it'll make someone happy down the line
> Convert (port/ip)-(to/from)-octet-buffer macros to inline functions

- backend/sbcl.lisp
:windows is added by trivial-features lib, so might work sometimes depending on what was loaded previously. Better to use something consistent though (or explicitly depend on trivial-features).
makes the workaround for #106 more reliable
> SBCL doesn't put :windows on *features*, use :win32 instead

- backend/sbcl.lisp
The default for nodelay was being ignored, which was confusing to read/debug and also different behavior from the rest of the backends.
> Fix default nodelay true on sbcl backend to actually work

- backend/clozure.lisp
- backend/lispworks.lisp
The broadcast hack for LispWorks is ultimately incorrect and should be reverted. I still have no satisfying solution to it but this kludge doesn't belong in USOCKET.
> [LW] revert broadcast hack

- backend/openmcl.lisp
Description:
usocket versions: all versions I've tried from 0.6.1 to 0.8.8 CCL version: Version 1.10-r16196  (LinuxX8664)
In the latest CCL version (Version 1.13 (v1.13) LinuxX8664), usocket's buggy function  has apparently been superseded by an ipv6 function, which is why the bug doesn't appear there. But usocket's non-ipv6 function may as well also be fixed, e.g. for use on old (or other non-ipv6) CCL's.
Bug demonstration:
; first open a listening udp socket on port 12000, e.g. with
;   nc -l -u -p 12000
; then run this test
(defun test ()
(let ((sock (socket-connect #(127 0 0 1) 12000 :protocol :datagram)))
(unwind-protect
(socket-send sock
(make-array 1 :element-type '(unsigned-byte 8)
:initial-element #x61)
1)
(sleep 1)
(socket-close sock))))
Observe the unexpected error:
> Error: …
> Bugfix for error sending a UDP datagram on CCL when host is a vector.

- backend/clisp.lisp
When creating the real-buffer array, the offset was neglected.
This patch also contains a performance improvement. The function sometimes made one more copy of the data than it needed to.
> Bugfix: clisp rawsock socket-send neglected offset

- backend/clisp.lisp
socket-send takes a buffer argument and offset/size args to specify which part of the buffer to send. But the ffi:allocate-deep function that it calls apparently does not. Although that function takes a count argument, count does not mean how many bytes of the buffer it should copy. The count argument is meant to say how big the buffer is. It isn't allowed to be smaller than the buffer's length. The way socket-send is written, it passes a smaller count than the buffer's length, causing an error.
This patch fixes socket-send.
Here is a udp echo server demonstrating the failure that this patch fixes.
(defun handle-datagram (dg)
(declare (type (simple-array (unsigned-byte 8) *) dg))
(print (map 'string #'code-char dg))
dg)
(defun start-socket-server ()
(socket-server #(127 0 0 1) 12000 …
> Bugfix: clisp ffi udp socket-send

- backend/clisp.lisp
socket-close was not written to be called more than once. However a finalizer was installed to call it, even though the user might already have explicitly called it already. This patch rewrites it to be callable more than once.
The original socket-close did two things, both of which were problematic if done twice.
1) It called ffi:foreign-free, which is not allowed to be called twice, so
produced a "double free or corruption" error from the underlying
malloc.
2) It closed an underlying file descriptor, which again by the time of
the second call, could have been re-alloted by the OS to a different
socket that had no desire to be closed.
Demonstrating the bug:
Run a udp echo server listening on port 12000. Then,
```
(defun client (n delay-seconds)
(dotimes (i n)
(let ((sock (socket-connect …
```
> Fix: clisp ffi udp corrupt memory and descriptors
